default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


development:
  <<: *default
  database: blog_rails_development
  host: localhost
  port: 5432
  username: myadmin
  password: StrongPass123

test:
  <<: *default
  database: blog_rails_test
  host: localhost
  port: 5432
  username: myadmin
  password: StrongPass123

production:
  primary: &primary_production
    <<: *default
    database: blog_rails_production
    username: blog_rails
    password: <%= ENV["BLOG_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: blog_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: blog_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: blog_rails_production_cable
    migrations_paths: db/cable_migrate
